### ISSUE TITLE
scp and ssh seems to impact earlier sendln commands

### ISSUE THREAD

**Issue by ClearaSound** [hymkor/expect#21] opened 2021-12-17 08:00 UTC
Hi,
Thanks for the tool.
I have found a workaround but thought best to check if this is expected behaviour

I am trying to script a number of actions but have a problem where all actions are in the same .lua script.
The script will be used to update an Ubuntu server(s) with some configuration from windows10
the script takes two arguments IP and Password and arg[] is used within the .lua
using sendln the script clears/updates the Known_hosts and remove files from a windows directory.
testing to this point works fine where no additional code exists

When I start adding the scp via the spawn commands the ALL sendln commands previously working stop working and as if they are getting bypassed

the script needs to execute mutiple scp and ssh command .

I tried adding a wait/sleep with no sucess

Splitting the .lua to do the clearing/update and then using sendln to execute a separate .lua to do the scp and ssh commands seems to have worked with the number of scp and ssh call so far with only issue having 

the attached is the script in one lua file where all the three sendln do not execute

Thanks

 
![lua sample](https://user-images.githubusercontent.com/96283033/146509799-6e9b5a4a-0b60-4684-b40c-5b2e71893d45.png)

**Comment by hymkor** [comment] 2021-12-18 02:55
Thank you for report.
報告ありがとうございます [Japanese translation]

It is possible that multiple ssh/scp processes would try to read only one single console-input, however, only one process could read it and others could not.
複数の ssh/scp のプロセスが一つのコンソール入力を読もうとして、そのうちの一つのプロセスしか読めず、他は読めていないということがありえます。

While the first ssh/scp process is running, it may read the console-input sent for the second ssh/scp process
最初の ssh/scp が生きているので、次の ssh/scp 向けの入力が、最初のプロセスに奪われているのかもしれません。

Though I could not reproduce your problem in my environment, I believe your workaround is one of the right solution.
私の環境ではうまく再現できないのですが、貴方の回避策は正しい解決の一つだと思います。

Or I may have to add the new functions
    - the function to wait that the process started by spawn() terminates 
    - the function to start process setting STDIN NUL

あるいはわたしは、spawn で起動したプロセスが終了するのを待つ関数や、標準入力に NUL をセットしてプロセスを起動する関数など、新しい関数を追加すべきかもしれません。

I am not sure what is the best solution.
自分も最適な方法について確信がありません。

If you have opinions, requests or ideas, please tell me.
もし、なにか意見やリクエスト、アイデアがあれば、教えてください。

**Comment by hymkor** [comment] 2021-12-18 05:46
I implemented `wait(PID)` function on the new version [v0.6.0](https://github.com/zetamatta/expect/releases/tag/v0.6.0)

If you use `wait(PID)` as below, the single script calling multiple ssh/scp processes may work as expected.

```lua
local pid1 = spawn("scp", ... )
if pid1 then
   -- 
   wait(pid1)
end

local pid2 = spawn("ssh", ... )
if pid2 then
   -- 
   wait(pid2)
end
```

**Comment by ClearaSound** [comment] 2021-12-19 21:54
Hi @zetamatta 
Thanks for your prompt response.
I will test the new version, re test and update.
also i forgot to mention I tried to use the spawn for the ssh-keygen and ssh-keyscan commands with the exact same result.

below is the image of the old version output on a command prompt window.. you can notice that the removal and update of the key did not take place and no output on the command prompt window to indicate that the commands were even attempted.

![image](https://user-images.githubusercontent.com/96283033/146692092-636e7f43-c71d-42d6-bf45-bbb3ac2ce5d3.png)

**Comment by ClearaSound** [comment] 2021-12-19 22:09
hi @zetamatta 
added the wait and the commands and now the keygen commands are getting executed with correct results..
I will add the same around all of the others and test if any impact to the expect / send sequences.

thanks again.

**Comment by hymkor** [comment] 2022-01-29 13:10
I would like to close this issue.
If your problem is not still resolved , could you reopen this issue ?

**Closed as completed by hymkor** 2022-01-29 13:10 UTC
Labels: enhancement
