### ISSUE TITLE
error message [syntax error] using example in Windows 10

### ISSUE THREAD

**Issue by wolf-li** [hymkor/expect#23] opened 2022-02-14 09:33 UTC
Hi, guys:
I get a error message when I run the example. Could anyone know that?

sample.lua
```lua
echo(true)
if spawn([[C:\Program Files\Git\usr\bin\ssh.exe]],"xxx@1xxxxx3") 
then
  expect("password:")
  echo(false)
  send("xxxxx\r")
  expect("~]$")
  echo(true)
  send("exit\r")
end
```

terrmial shows error message:
sample.lua at EOF:   syntax error

**Comment by hymkor** [comment] 2022-02-14 10:57
@wolf-li 

Thank you for reporting.

Would you append CRLF at the last line of sample.lua ?

On my environment, when I remove CRLF from the last line of the script, I see the error message you reported.

**Comment by wolf-li** [comment] 2022-02-14 12:30
@hymkor 

Thank you very much for your reply. I tried the method you said, but it didn't work.  As shown in the figure below .  
Using expect-v0.6.0-amd64.zip and v0.5, It's the same problem.

![export](https://user-images.githubusercontent.com/59823739/153864578-08c10732-f2a8-41dc-8875-aab4ba099e2d.png)

**Comment by hymkor** [comment] 2022-02-14 12:44
@wolf-li :

When you edit the script by Visual Studio Code, it is possible that the last line does not have CRLF.

To resolve this problem , two methods exist.

1. Append the empty line after `end` .
2. Try the new version: [Release v0.6.1 · hymkor/expect](https://github.com/hymkor/expect/releases/tag/v0.6.1).  
where I fixed the bug that [When a script did not end with CRLF, the last line was ignored.](https://github.com/hymkor/expect/commit/3609706a90bc68d4c147a2fdc7d16556ba120617)

Would you try one of these methods ?

**Comment by wolf-li** [comment] 2022-02-14 12:59
> @wolf-li :
> 
> When you edit the script by Visual Studio Code, it is possible that the last line does not have CRLF.
> 
> To resolve this problem , two methods exist.
> 
> 1. Append the empty line after `end` .
> 2. Try the new version: [Release v0.6.1 · hymkor/expect](https://github.com/hymkor/expect/releases/tag/v0.6.1).
>    where I fixed the bug that [When a script did not end with CRLF, the last line was ignored.](https://github.com/hymkor/expect/commit/3609706a90bc68d4c147a2fdc7d16556ba120617)
> 
> Would you try one of these methods ?

Good job, All of these solutions can solve the problem.
But I recommend using the second method. If the script is written incorrectly, the session will not get stuck as shown in the figure below. 


![export2](https://user-images.githubusercontent.com/59823739/153869945-b656f688-213f-4292-a566-685016bdd751.png)

Many thanks to the author for his work.

**Comment by hymkor** [comment] 2022-02-14 13:05
I'm glad the problem is solved .

Can I close this issue ?

**Comment by wolf-li** [comment] 2022-02-14 13:09
Yes. Thanks for your work.

**Closed as completed** 2022-02-14 13:14 UTC
Labels: bug
